# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  Major: '0'
  Minor: '1'
  buildConfiguration: 'Release'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '**/*.csproj'
    
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Run dotnet build  $(buildConfiguration)'

- script: dotnet test test/RulesChain.UnitTest/RulesChain.UnitTest.csproj --logger trx
  displayName: 'dotnet test RulesChain.UnitTest'
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: dotnet pack /p:PackageVersion='$(Major).$(Minor).$(Build.BuildId)' --configuration $(buildConfiguration)
  displayName: 'Packing projects'

- script: dotnet nuget push /home/vsts/work/1/s/src/RulesChain.Contracts/bin/Release/RulesChain.Contracts.0.1.18.nupkg -k $(nuget.key) -s https://api.nuget.org/v3/index.json
  displayName: 'Pushing RulesChain.Contracts to Nuget.org'

- script: dotnet nuget push /home/vsts/work/1/s/src/RulesChain.Contracts/bin/Release/RulesChain.0.1.18.nupkg -k $(nuget.key) -s https://api.nuget.org/v3/index.json
  displayName: 'Pushing RulesChain.Contracts to Nuget.org'